# Generated by Django 4.2.28 on 2026-03-30 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(max_length=50)),
                ('base_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'accounts_ai_provider',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_organization',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ai_api_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('ai_model', models.CharField(default='gpt-4o-mini', max_length=100)),
                ('monthly_token_budget', models.IntegerField(default=100000)),
                ('tokens_used_this_month', models.IntegerField(default=0)),
                ('jira_base_url', models.URLField(blank=True, null=True)),
                ('jira_project_key', models.CharField(blank=True, max_length=100, null=True)),
                ('github_org', models.CharField(blank=True, max_length=150, null=True)),
                ('github_repo', models.CharField(blank=True, max_length=150, null=True)),
                ('jenkins_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='accounts.aiprovider')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='accounts.organization')),
            ],
            options={
                'db_table': 'accounts_team',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('platform_owner', 'Platform Owner'), ('org_admin', 'Org Admin'), ('team_manager', 'Team Manager'), ('tester', 'Tester'), ('viewer', 'Viewer')], default='tester', max_length=30)),
                ('jira_token', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('github_token', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('notification_provider', models.CharField(choices=[('none', 'None'), ('slack', 'Slack'), ('teams', 'Microsoft Teams')], default='none', max_length=20)),
                ('slack_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('slack_username', models.CharField(blank=True, max_length=100, null=True)),
                ('teams_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='accounts.organization')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='accounts.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_user_profile',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
