# Generated by Django 4.2.28 on 2026-02-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('QA_LEAD', 'QA Lead'), ('TESTER', 'Tester')], default='TESTER', max_length=20),
        ),
    ]
