# Generated by Codex on 2026-04-01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def _map_profile_role_to_membership_role(profile_role: str | None) -> str:
    if profile_role == "team_manager":
        return "manager"
    if profile_role == "viewer":
        return "viewer"
    return "tester"


def _set_primary_membership(TeamMembership, user_id, membership):
    TeamMembership.objects.filter(
        user_id=user_id,
        is_primary=True,
        is_active=True,
    ).exclude(pk=membership.pk).update(is_primary=False)

    if not membership.is_primary:
        membership.is_primary = True
        membership.save(update_fields=["is_primary"])


def _ensure_membership(TeamMembership, *, user_id, team_id, role, is_primary):
    membership, created = TeamMembership.objects.get_or_create(
        user_id=user_id,
        team_id=team_id,
        defaults={
            "role": role,
            "is_primary": is_primary,
            "is_active": True,
        },
    )

    update_fields = []

    if membership.role != role and role == "manager":
        membership.role = role
        update_fields.append("role")

    if not membership.is_active:
        membership.is_active = True
        update_fields.append("is_active")

    if update_fields:
        membership.save(update_fields=update_fields)

    if is_primary:
        _set_primary_membership(TeamMembership, user_id, membership)

    return membership


def forwards(apps, schema_editor):
    Team = apps.get_model("accounts", "Team")
    TeamMembership = apps.get_model("accounts", "TeamMembership")
    UserProfile = apps.get_model("accounts", "UserProfile")

    for profile in UserProfile.objects.exclude(team_id__isnull=True):
        _ensure_membership(
            TeamMembership,
            user_id=profile.user_id,
            team_id=profile.team_id,
            role=_map_profile_role_to_membership_role(profile.role),
            is_primary=True,
        )

    for team in Team.objects.exclude(manager_id__isnull=True):
        membership = _ensure_membership(
            TeamMembership,
            user_id=team.manager_id,
            team_id=team.id,
            role="manager",
            is_primary=False,
        )

        has_primary = TeamMembership.objects.filter(
            user_id=team.manager_id,
            is_primary=True,
            is_active=True,
        ).exists()
        if not has_primary:
            _set_primary_membership(TeamMembership, team.manager_id, membership)


def backwards(apps, schema_editor):
    TeamMembership = apps.get_model("accounts", "TeamMembership")
    TeamMembership.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("role", models.CharField(choices=[("manager", "Manager"), ("tester", "Tester"), ("viewer", "Viewer")], default="viewer", max_length=20)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="accounts.team")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="team_memberships", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "accounts_team_membership",
                "ordering": ["team__name", "user__first_name", "user__last_name"],
                "unique_together": {("team", "user")},
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(is_active=True, is_primary=True),
                        fields=("user",),
                        name="accounts_unique_primary_active_team_membership",
                    )
                ],
            },
        ),
        migrations.RunPython(forwards, backwards),
    ]
