# Generated by Django 4.2.28 on 2026-04-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_team_ai_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamaiconfig',
            name='monthly_budget',
            field=models.IntegerField(default=1000000),
        ),
    ]
