# Generated by Django 4.2.28 on 2026-05-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_teamaiconfig_monthly_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='ai_api_key',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ai_model',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ai_provider',
        ),
        migrations.RemoveField(
            model_name='team',
            name='github_org',
        ),
        migrations.RemoveField(
            model_name='team',
            name='github_repo',
        ),
        migrations.RemoveField(
            model_name='team',
            name='jenkins_url',
        ),
        migrations.RemoveField(
            model_name='team',
            name='jira_base_url',
        ),
        migrations.RemoveField(
            model_name='team',
            name='jira_project_key',
        ),
        migrations.RemoveField(
            model_name='team',
            name='monthly_token_budget',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tokens_used_this_month',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='github_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='jira_token',
        ),
    ]
