# Generated by Codex on 2026-05-11

from django.db import migrations, models


def seed_ai_providers(apps, schema_editor):
    AIProvider = apps.get_model("accounts", "AIProvider")
    providers = [
        {
            "provider_type": "anthropic",
            "name": "Anthropic",
            "base_url": "https://api.anthropic.com/v1",
        },
        {
            "provider_type": "azure_openai",
            "name": "Azure OpenAI",
            "base_url": "",
        },
        {
            "provider_type": "groq",
            "name": "Groq",
            "base_url": "https://api.groq.com/openai/v1",
        },
        {
            "provider_type": "ollama",
            "name": "Ollama",
            "base_url": "http://localhost:11434",
        },
        {
            "provider_type": "openai",
            "name": "OpenAI",
            "base_url": "https://api.openai.com/v1",
        },
    ]

    for provider_data in providers:
        provider = AIProvider.objects.filter(
            provider_type=provider_data["provider_type"]
        ).first()
        if provider is None:
            AIProvider.objects.create(
                provider_type=provider_data["provider_type"],
                name=provider_data["name"],
                base_url=provider_data["base_url"],
                is_active=True,
            )
        else:
            provider.name = provider_data["name"]
            provider.base_url = provider_data["base_url"]
            provider.is_active = True
            provider.save(update_fields=["name", "base_url", "is_active"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_team_ai_api_key_remove_team_ai_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamaiconfig",
            name="api_version",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="teamaiconfig",
            name="endpoint_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="modelprofile",
            name="deployment_mode",
            field=models.CharField(
                choices=[("cloud", "Cloud"), ("local", "Local")],
                default="cloud",
                max_length=20,
            ),
        ),
        migrations.RunPython(seed_ai_providers, migrations.RunPython.noop),
    ]
