# Generated by Django 4.2.28 on 2026-04-13 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('projects', '0001_initial'),
        ('accounts', '0004_team_ai_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_slug', models.CharField(max_length=50)),
                ('repo_identifier', models.CharField(max_length=255)),
                ('default_branch', models.CharField(default='main', max_length=150)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_repository_bindings', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_bindings', to='projects.project')),
            ],
            options={
                'db_table': 'integrations_repository_binding',
                'ordering': ['project__name', 'provider_slug', 'repo_identifier'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_slug', models.CharField(max_length=50)),
                ('action_type', models.CharField(max_length=100)),
                ('request_json', models.JSONField(blank=True, default=dict)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_action_logs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_action_logs', to='projects.project')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_action_logs', to='accounts.team')),
            ],
            options={
                'db_table': 'integrations_integration_action_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalIssueLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_slug', models.CharField(max_length=50)),
                ('external_key', models.CharField(max_length=100)),
                ('external_url', models.URLField(blank=True)),
                ('object_id', models.CharField(max_length=64)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_external_issue_links', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_issue_links', to='projects.project')),
            ],
            options={
                'db_table': 'integrations_external_issue_link',
                'ordering': ['project__name', 'provider_slug', 'external_key'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_slug', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=150, null=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('headers_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='projects.project')),
                ('repository_binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='integrations.repositorybinding')),
            ],
            options={
                'db_table': 'integrations_webhook_event',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['provider_slug', 'event_type', 'status'], name='int_webhook_provider_idx'), models.Index(fields=['project', 'received_at'], name='int_webhook_project_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False), models.Q(('external_id', ''), _negated=True)), fields=('provider_slug', 'external_id'), name='integrations_unique_provider_webhook_external_id'),
        ),
        migrations.AddIndex(
            model_name='repositorybinding',
            index=models.Index(fields=['provider_slug', 'repo_identifier'], name='int_repo_provider_idx'),
        ),
        migrations.AddIndex(
            model_name='repositorybinding',
            index=models.Index(fields=['project', 'is_active'], name='int_repo_project_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='repositorybinding',
            constraint=models.UniqueConstraint(fields=('project', 'provider_slug', 'repo_identifier'), name='integrations_unique_project_repository_binding'),
        ),
        migrations.AddIndex(
            model_name='integrationactionlog',
            index=models.Index(fields=['provider_slug', 'action_type', 'status'], name='int_action_provider_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationactionlog',
            index=models.Index(fields=['project', 'created_at'], name='int_action_project_idx'),
        ),
        migrations.AddIndex(
            model_name='externalissuelink',
            index=models.Index(fields=['project', 'provider_slug', 'external_key'], name='int_issue_project_idx'),
        ),
        migrations.AddIndex(
            model_name='externalissuelink',
            index=models.Index(fields=['content_type', 'object_id'], name='int_issue_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalissuelink',
            constraint=models.UniqueConstraint(fields=('project', 'provider_slug', 'external_key', 'content_type', 'object_id'), name='integrations_unique_external_issue_link'),
        ),
    ]
