from django.urls import path

from apps.automation.views import (
    AutomationScriptActivateView,
    AutomationScriptDeactivateView,
    AutomationScriptDetailView,
    AutomationScriptListCreateView,
    AutomationScriptValidateView,
    ExecutionScheduleDetailView,
    ExecutionScheduleListCreateView,
    ExecutionScheduleTriggerView,
    ExecutionStepDetailView,
    ExecutionStepListView,
    TestExecutionDetailView,
    TestExecutionListCreateView,
    TestExecutionPauseView,
    TestExecutionResumeView,
    TestExecutionStopView,
    TestResultDetailView,
    TestResultExportJunitView,
)

urlpatterns = [
    path(
        "automation-scripts/",
        AutomationScriptListCreateView.as_view(),
        name="automation-script-list-create",
    ),
    path(
        "automation-scripts/<uuid:pk>/",
        AutomationScriptDetailView.as_view(),
        name="automation-script-detail",
    ),
    path(
        "automation-scripts/<uuid:pk>/activate/",
        AutomationScriptActivateView.as_view(),
        name="automation-script-activate",
    ),
    path(
        "automation-scripts/<uuid:pk>/deactivate/",
        AutomationScriptDeactivateView.as_view(),
        name="automation-script-deactivate",
    ),
    path(
        "automation-scripts/<uuid:pk>/validate/",
        AutomationScriptValidateView.as_view(),
        name="automation-script-validate",
    ),
    path(
        "test-executions/",
        TestExecutionListCreateView.as_view(),
        name="test-execution-list-create",
    ),
    path(
        "test-executions/<uuid:pk>/",
        TestExecutionDetailView.as_view(),
        name="test-execution-detail",
    ),
    path(
        "test-executions/<uuid:pk>/pause/",
        TestExecutionPauseView.as_view(),
        name="test-execution-pause",
    ),
    path(
        "test-executions/<uuid:pk>/resume/",
        TestExecutionResumeView.as_view(),
        name="test-execution-resume",
    ),
    path(
        "test-executions/<uuid:pk>/stop/",
        TestExecutionStopView.as_view(),
        name="test-execution-stop",
    ),
    path(
        "test-executions/<uuid:execution_pk>/steps/",
        ExecutionStepListView.as_view(),
        name="execution-step-list",
    ),
    path(
        "test-executions/<uuid:execution_pk>/steps/<uuid:pk>/",
        ExecutionStepDetailView.as_view(),
        name="execution-step-detail",
    ),
    path(
        "test-executions/<uuid:execution_pk>/result/",
        TestResultDetailView.as_view(),
        name="test-result-detail",
    ),
    path(
        "test-executions/<uuid:execution_pk>/result/export-junit/",
        TestResultExportJunitView.as_view(),
        name="test-result-export-junit",
    ),
    path(
        "execution-schedules/",
        ExecutionScheduleListCreateView.as_view(),
        name="execution-schedule-list-create",
    ),
    path(
        "execution-schedules/<uuid:pk>/",
        ExecutionScheduleDetailView.as_view(),
        name="execution-schedule-detail",
    ),
    path(
        "execution-schedules/<uuid:pk>/trigger/",
        ExecutionScheduleTriggerView.as_view(),
        name="execution-schedule-trigger",
    ),
]
