# settings.py
"""
Django settings for biat_testmanager project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from decouple import config
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# Encryption key for encrypted model fields
FIELD_ENCRYPTION_KEY = config('FIELD_ENCRYPTION_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'daphne',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    #third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'channels',
    'corsheaders',
    'encrypted_model_fields',
    'rest_framework_simplejwt.token_blacklist',
    

    'apps.accounts.apps.AccountsConfig',
    'apps.ai.apps.AIConfig',
    'apps.projects.apps.ProjectsConfig',
    'apps.specs.apps.SpecsConfig',
    'apps.testing.apps.TestingConfig',
    'apps.automation.apps.AutomationConfig',
    'apps.integrations.apps.IntegrationsConfig',
]



# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

AUTHENTICATION_BACKENDS = [
    'apps.accounts.backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# JWT Settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",   # Vite
    "http://127.0.0.1:5173",   # Vite
]


CORS_ALLOW_CREDENTIALS = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'biat_testmanager.urls'
ASGI_APPLICATION = "biat_testmanager.asgi.application"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'biat_testmanager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='biat_db'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SPEC_EMBEDDING_MODEL_NAME = config(
    "SPEC_EMBEDDING_MODEL_NAME",
    default="BAAI/bge-m3",
)
SPEC_EMBEDDING_LOCAL_FILES_ONLY = config(
    "SPEC_EMBEDDING_LOCAL_FILES_ONLY",
    default=False,
    cast=bool,
)
SPEC_EMBEDDING_DEVICE_PREFERENCE = config(
    "SPEC_EMBEDDING_DEVICE_PREFERENCE",
    default="auto",
)
SPEC_EMBEDDING_BATCH_SIZE = config(
    "SPEC_EMBEDDING_BATCH_SIZE",
    default=2,
    cast=int,
)
SPEC_EMBEDDING_MAX_LENGTH = config(
    "SPEC_EMBEDDING_MAX_LENGTH",
    default=1024,
    cast=int,
)
SPEC_EMBEDDING_VECTOR_DIMENSIONS = config(
    "SPEC_EMBEDDING_VECTOR_DIMENSIONS",
    default=1024,
    cast=int,
)
SPEC_EMBEDDING_NORMALIZE = config(
    "SPEC_EMBEDDING_NORMALIZE",
    default=True,
    cast=bool,
)
SPEC_CHUNK_STRATEGY = config(
    "SPEC_CHUNK_STRATEGY",
    default="structure_aware_v1",
)
SPEC_CHUNK_MAX_CHARS = config(
    "SPEC_CHUNK_MAX_CHARS",
    default=1400,
    cast=int,
)
SPEC_CHUNK_OVERLAP_CHARS = config(
    "SPEC_CHUNK_OVERLAP_CHARS",
    default=120,
    cast=int,
)
MLFLOW_TRACKING_URI = config(
    "MLFLOW_TRACKING_URI",
    default=f"sqlite:///{(BASE_DIR / 'mlflow.db').as_posix()}",
)
MLFLOW_ARTIFACT_ROOT = config(
    "MLFLOW_ARTIFACT_ROOT",
    default=(BASE_DIR / "mlruns").resolve().as_uri(),
)
MLFLOW_EXPERIMENT_NAME = config(
    "MLFLOW_EXPERIMENT_NAME",
    default="biat-test-manager-specs",
)

CELERY_BROKER_URL = config(
    "CELERY_BROKER_URL",
    default="redis://localhost:6379/0",
)
CELERY_RESULT_BACKEND = config(
    "CELERY_RESULT_BACKEND",
    default=CELERY_BROKER_URL,
)
CHANNEL_REDIS_URL = config(
    "CHANNEL_REDIS_URL",
    default=CELERY_BROKER_URL,
)
REDIS_URL = config("REDIS_URL", default=CELERY_BROKER_URL)
RUNNING_TESTS = "test" in sys.argv
if RUNNING_TESTS:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [CHANNEL_REDIS_URL],
            },
        },
    }
CELERY_TASK_ALWAYS_EAGER = config(
    "CELERY_TASK_ALWAYS_EAGER",
    default=False,
    cast=bool,
)
CELERY_TASK_EAGER_PROPAGATES = config(
    "CELERY_TASK_EAGER_PROPAGATES",
    default=True,
    cast=bool,
)

# Three queues, one per workload. See docs/roadmap.md Step 1 and
# docs/PLATFORM.md hard rule 9.
#   ai_agent    — long-lived LangGraph sessions (gevent worker recommended)
#   regression  — bulk dispatch of saved scripts from planned/standalone runs
#   interactive — single executions, debug rerun, manual browser sessions
try:
    from kombu import Queue as _KombuQueue
    CELERY_TASK_QUEUES = (
        _KombuQueue("ai_agent", routing_key="ai_agent"),
        _KombuQueue("regression", routing_key="regression"),
        _KombuQueue("interactive", routing_key="interactive"),
    )
except ModuleNotFoundError:  # pragma: no cover - environment without celery
    CELERY_TASK_QUEUES = ()

CELERY_TASK_DEFAULT_QUEUE = "regression"
CELERY_TASK_DEFAULT_ROUTING_KEY = "regression"
CELERY_TASK_ROUTES = {
    "ai.run_generation_session": {"queue": "ai_agent"},
    "ai.run_authoring_session": {"queue": "ai_agent"},
    "automation.run_test_execution": {"queue": "regression"},
    "automation.run_manual_browser_session": {"queue": "interactive"},
    "automation.expire_stale_execution_checkpoints": {"queue": "regression"},
    # Future tasks (not yet implemented — listed for traceability):
    # "ai.run_agent_session": {"queue": "ai_agent"},
    # "ai.generate_failure_rca": {"queue": "ai_agent"},
    # "ai.generate_tests_from_spec": {"queue": "ai_agent"},
    # "automation.run_single_execution": {"queue": "interactive"},
    # "automation.debug_rerun": {"queue": "interactive"},
}

CELERY_BEAT_SCHEDULE = {
    "expire-stale-execution-checkpoints": {
        "task": "automation.expire_stale_execution_checkpoints",
        "schedule": 300.0,
    },
}
MINIO_ENDPOINT_URL = config("MINIO_ENDPOINT_URL", default="http://localhost:9000")
MINIO_RUNNER_ENDPOINT_URL = config(
    "MINIO_RUNNER_ENDPOINT_URL",
    default="http://minio:9000",
)
MINIO_ACCESS_KEY = config("MINIO_ACCESS_KEY", default="biat")
MINIO_SECRET_KEY = config("MINIO_SECRET_KEY", default="biat-secret")
MINIO_BUCKET_NAME = config("MINIO_BUCKET_NAME", default="biat-artifacts")
MINIO_REGION_NAME = config("MINIO_REGION_NAME", default="us-east-1")
AUTOMATION_DEFAULT_BROWSER = config(
    "AUTOMATION_DEFAULT_BROWSER",
    default="chromium",
)
AUTOMATION_DEFAULT_PLATFORM = config(
    "AUTOMATION_DEFAULT_PLATFORM",
    default="desktop",
)
SELENOID_HUB_URL = config("SELENOID_HUB_URL", default="http://localhost:4444/wd/hub")
SELENOID_RUNNER_HUB_URL = config(
    "SELENOID_RUNNER_HUB_URL",
    default="http://selenoid:4444/wd/hub",
)
SELENOID_PUBLIC_URL = config("SELENOID_PUBLIC_URL", default=SELENOID_HUB_URL)
AUTOMATION_RUNNER_DOCKER_NETWORK = config(
    "AUTOMATION_RUNNER_DOCKER_NETWORK",
    default="biat_selenoid",
)
AUTOMATION_PYTHON_RUNNER_IMAGE = config(
    "AUTOMATION_PYTHON_RUNNER_IMAGE",
    default="biat-runner-python:latest",
)
AUTOMATION_JAVA_RUNNER_IMAGE = config(
    "AUTOMATION_JAVA_RUNNER_IMAGE",
    default="biat-runner-java:latest",
)
AUTOMATION_STREAM_HOLD_SECONDS = config(
    "AUTOMATION_STREAM_HOLD_SECONDS",
    default=20,
    cast=int,
)

# AI live browser authoring (Selenoid today, Moon later).
# Authoring runs on the ai_agent Celery queue and drives Selenoid via
# Selenium-Remote. The runner-container pipeline used by regression
# (`automation.run_test_execution`) is not involved here.
AI_AUTHORING_DEFAULT_BROWSER = config("AI_AUTHORING_DEFAULT_BROWSER", default="chrome")
# Empty means "use Selenoid's default version". Set explicitly (e.g. "120.0")
# only when the team wants to pin to an image from infra/selenoid/browsers.json.
AI_AUTHORING_DEFAULT_BROWSER_VERSION = config(
    "AI_AUTHORING_DEFAULT_BROWSER_VERSION",
    default="",
)
AI_AUTHORING_SESSION_TIMEOUT = config("AI_AUTHORING_SESSION_TIMEOUT", default="10m")
AI_AUTHORING_ENABLE_VNC = config("AI_AUTHORING_ENABLE_VNC", default=True, cast=bool)
AI_AUTHORING_ENABLE_VIDEO = config("AI_AUTHORING_ENABLE_VIDEO", default=False, cast=bool)
AI_AUTHORING_OBSERVE_TIMEOUT_SECONDS = config(
    "AI_AUTHORING_OBSERVE_TIMEOUT_SECONDS",
    default=30,
    cast=int,
)
AI_AUTHORING_ACTION_TIMEOUT_SECONDS = config(
    "AI_AUTHORING_ACTION_TIMEOUT_SECONDS",
    default=30,
    cast=int,
)
AI_AUTHORING_VISUAL_ACTION_DELAY_MS = config(
    "AI_AUTHORING_VISUAL_ACTION_DELAY_MS",
    default=250,
    cast=int,
)
AI_AUTHORING_TYPE_DELAY_MS = config(
    "AI_AUTHORING_TYPE_DELAY_MS",
    default=25,
    cast=int,
)

# Per-session AI authoring knobs surfaced in the UI (request scope).
# Defaults below are used when the request omits the field. Hard caps below
# are the upper bound the serializer enforces — they protect the system from
# runaway sessions / output budgets regardless of what the UI sends.
AI_AUTHORING_DEFAULT_MAX_STEPS = config(
    "AI_AUTHORING_DEFAULT_MAX_STEPS",
    default=12,
    cast=int,
)
AI_AUTHORING_MAX_STEPS_LIMIT = config(
    "AI_AUTHORING_MAX_STEPS_LIMIT",
    default=50,
    cast=int,
)
AI_AUTHORING_DEFAULT_TEMPERATURE = config(
    "AI_AUTHORING_DEFAULT_TEMPERATURE",
    default=0.0,
    cast=float,
)
AI_AUTHORING_DEFAULT_MAX_TOKENS_PER_STEP = config(
    "AI_AUTHORING_DEFAULT_MAX_TOKENS_PER_STEP",
    default=500,
    cast=int,
)
AI_AUTHORING_MAX_TOKENS_PER_STEP_LIMIT = config(
    "AI_AUTHORING_MAX_TOKENS_PER_STEP_LIMIT",
    default=2000,
    cast=int,
)

