# settings.py
"""
Django settings for biat_testmanager project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from decouple import config
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# Encryption key for encrypted model fields
FIELD_ENCRYPTION_KEY = config('FIELD_ENCRYPTION_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    #third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'channels',
    'corsheaders',
    'encrypted_model_fields',
    'rest_framework_simplejwt.token_blacklist',
    

    'apps.accounts.apps.AccountsConfig',
    'apps.projects.apps.ProjectsConfig',
    'apps.specs.apps.SpecsConfig',
    'apps.testing.apps.TestingConfig',
    'apps.automation.apps.AutomationConfig',
    'apps.integrations.apps.IntegrationsConfig',
]



# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

AUTHENTICATION_BACKENDS = [
    'apps.accounts.backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# JWT Settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",   # Vite
    "http://127.0.0.1:5173",   # Vite
]


CORS_ALLOW_CREDENTIALS = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'biat_testmanager.urls'
ASGI_APPLICATION = "biat_testmanager.asgi.application"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'biat_testmanager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='biat_db'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SPEC_EMBEDDING_MODEL_NAME = config(
    "SPEC_EMBEDDING_MODEL_NAME",
    default="BAAI/bge-m3",
)
SPEC_EMBEDDING_LOCAL_FILES_ONLY = config(
    "SPEC_EMBEDDING_LOCAL_FILES_ONLY",
    default=False,
    cast=bool,
)
SPEC_EMBEDDING_DEVICE_PREFERENCE = config(
    "SPEC_EMBEDDING_DEVICE_PREFERENCE",
    default="auto",
)
SPEC_EMBEDDING_BATCH_SIZE = config(
    "SPEC_EMBEDDING_BATCH_SIZE",
    default=2,
    cast=int,
)
SPEC_EMBEDDING_MAX_LENGTH = config(
    "SPEC_EMBEDDING_MAX_LENGTH",
    default=1024,
    cast=int,
)
SPEC_EMBEDDING_VECTOR_DIMENSIONS = config(
    "SPEC_EMBEDDING_VECTOR_DIMENSIONS",
    default=1024,
    cast=int,
)
SPEC_EMBEDDING_NORMALIZE = config(
    "SPEC_EMBEDDING_NORMALIZE",
    default=True,
    cast=bool,
)
SPEC_CHUNK_STRATEGY = config(
    "SPEC_CHUNK_STRATEGY",
    default="structure_aware_v1",
)
SPEC_CHUNK_MAX_CHARS = config(
    "SPEC_CHUNK_MAX_CHARS",
    default=1400,
    cast=int,
)
SPEC_CHUNK_OVERLAP_CHARS = config(
    "SPEC_CHUNK_OVERLAP_CHARS",
    default=120,
    cast=int,
)
MLFLOW_TRACKING_URI = config(
    "MLFLOW_TRACKING_URI",
    default=f"sqlite:///{(BASE_DIR / 'mlflow.db').as_posix()}",
)
MLFLOW_ARTIFACT_ROOT = config(
    "MLFLOW_ARTIFACT_ROOT",
    default=(BASE_DIR / "mlruns").resolve().as_uri(),
)
MLFLOW_EXPERIMENT_NAME = config(
    "MLFLOW_EXPERIMENT_NAME",
    default="biat-test-manager-specs",
)

CELERY_BROKER_URL = config(
    "CELERY_BROKER_URL",
    default="redis://localhost:6379/0",
)
CELERY_RESULT_BACKEND = config(
    "CELERY_RESULT_BACKEND",
    default=CELERY_BROKER_URL,
)
CHANNEL_REDIS_URL = config(
    "CHANNEL_REDIS_URL",
    default=CELERY_BROKER_URL,
)
RUNNING_TESTS = "test" in sys.argv
if RUNNING_TESTS:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [CHANNEL_REDIS_URL],
            },
        },
    }
CELERY_TASK_ALWAYS_EAGER = config(
    "CELERY_TASK_ALWAYS_EAGER",
    default=False,
    cast=bool,
)
CELERY_TASK_EAGER_PROPAGATES = config(
    "CELERY_TASK_EAGER_PROPAGATES",
    default=True,
    cast=bool,
)
CELERY_BEAT_SCHEDULE = {
    "expire-stale-execution-checkpoints": {
        "task": "automation.expire_stale_execution_checkpoints",
        "schedule": 300.0,
    },
}
AUTOMATION_ARTIFACTS_ROOT = Path(
    config(
        "AUTOMATION_ARTIFACTS_ROOT",
        default=str((MEDIA_ROOT / "automation_artifacts").resolve()),
    )
)
AUTOMATION_DEFAULT_BROWSER = config(
    "AUTOMATION_DEFAULT_BROWSER",
    default="chromium",
)
AUTOMATION_DEFAULT_PLATFORM = config(
    "AUTOMATION_DEFAULT_PLATFORM",
    default="desktop",
)
AUTOMATION_PLAYWRIGHT_PYTHON_BIN = config(
    "AUTOMATION_PLAYWRIGHT_PYTHON_BIN",
    default="python",
)
AUTOMATION_PLAYWRIGHT_WORKDIR = config(
    "AUTOMATION_PLAYWRIGHT_WORKDIR",
    default=str(BASE_DIR),
)
AUTOMATION_SELENIUM_PYTHON_BIN = config(
    "AUTOMATION_SELENIUM_PYTHON_BIN",
    default=AUTOMATION_PLAYWRIGHT_PYTHON_BIN,
)
AUTOMATION_SELENIUM_WORKDIR = config(
    "AUTOMATION_SELENIUM_WORKDIR",
    default=AUTOMATION_PLAYWRIGHT_WORKDIR,
)

