# Generated by Django 4.2.28 on 2026-04-12 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone
import uuid


def _infer_embedding_provider(model_name: str) -> str:
    normalized_name = (model_name or "").strip()
    if not normalized_name:
        return "local"
    if (
        "\\" in normalized_name
        or ":" in normalized_name
        or normalized_name.startswith((".", "/"))
    ):
        return "local"
    if "/" in normalized_name:
        return normalized_name.split("/", maxsplit=1)[0]
    return "local"


def backfill_embedding_metadata(apps, schema_editor):
    EmbeddingModel = apps.get_model("specs", "EmbeddingModel")
    SpecChunk = apps.get_model("specs", "SpecChunk")
    Specification = apps.get_model("specs", "Specification")

    model_name = getattr(settings, "SPEC_EMBEDDING_MODEL_NAME", "BAAI/bge-m3")
    dimensions = getattr(settings, "SPEC_EMBEDDING_VECTOR_DIMENSIONS", 1024)
    normalize = getattr(settings, "SPEC_EMBEDDING_NORMALIZE", True)

    embedding_model, _ = EmbeddingModel.objects.get_or_create(
        name=model_name,
        defaults={
            "provider": _infer_embedding_provider(model_name),
            "dimensions": dimensions,
            "normalize": normalize,
            "is_active": True,
        },
    )

    SpecChunk.objects.filter(
        embedding_vector__isnull=False,
        embedding_model_config__isnull=True,
    ).update(
        embedding_model=model_name,
        embedding_model_config=embedding_model,
    )

    indexed_specification_ids = list(
        SpecChunk.objects.filter(embedding_vector__isnull=False)
        .values_list("specification_id", flat=True)
        .distinct()
    )
    if indexed_specification_ids:
        Specification.objects.filter(id__in=indexed_specification_ids).update(
            index_status="indexed",
            indexed_at=timezone.now(),
        )
    Specification.objects.exclude(id__in=indexed_specification_ids).update(
        index_status="pending",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0004_specification_content_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('provider', models.CharField(blank=True, max_length=120)),
                ('dimensions', models.PositiveIntegerField()),
                ('normalize', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'specs_embedding_model',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='specification',
            name='index_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='specification',
            name='index_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('indexed', 'Indexed'), ('failed', 'Failed'), ('stale', 'Stale')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='specification',
            name='indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specchunk',
            name='embedding_model_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_chunks', to='specs.embeddingmodel'),
        ),
        migrations.RunPython(backfill_embedding_metadata, migrations.RunPython.noop),
    ]
