# Generated by Django 4.2.28 on 2026-04-02 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0003_testcase_linked_specifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationScript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('framework', models.CharField(choices=[('playwright', 'Playwright'), ('selenium', 'Selenium')], max_length=20)),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('java', 'Java')], max_length=20)),
                ('script_content', models.TextField()),
                ('script_version', models.IntegerField(default=1)),
                ('generated_by', models.CharField(choices=[('ai', 'AI'), ('user', 'User')], default='user', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='testing.testcase')),
            ],
            options={
                'db_table': 'automation_automation_script',
                'ordering': ['test_case__title', 'framework', 'language', '-script_version'],
                'unique_together': {('test_case', 'framework', 'language', 'script_version')},
            },
        ),
        migrations.CreateModel(
            name='ExecutionStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_index', models.IntegerField()),
                ('action', models.CharField(max_length=255)),
                ('target_element', models.CharField(max_length=500)),
                ('selector_used', models.CharField(blank=True, max_length=1000, null=True)),
                ('input_value', models.CharField(blank=True, max_length=1000, null=True)),
                ('screenshot_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'automation_execution_step',
                'ordering': ['execution__started_at', 'step_index'],
            },
        ),
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('ci_cd', 'CI/CD'), ('scheduled', 'Scheduled'), ('webhook', 'Webhook'), ('nightly', 'Nightly')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('paused', 'Paused'), ('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('browser', models.CharField(choices=[('chromium', 'Chromium'), ('firefox', 'Firefox'), ('webkit', 'WebKit'), ('chrome', 'Chrome'), ('edge', 'Edge')], default='chromium', max_length=20)),
                ('platform', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')], default='desktop', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('pause_requested', models.BooleanField(default=False)),
                ('agent_run', models.UUIDField(blank=True, null=True)),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='automation.automationscript')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='testing.testcase')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_test_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'automation_test_execution',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('error', 'Error')], max_length=20)),
                ('duration_ms', models.IntegerField(default=0)),
                ('total_steps', models.IntegerField(default=0)),
                ('passed_steps', models.IntegerField(default=0)),
                ('failed_steps', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('junit_xml', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('artifacts_path', models.FileField(blank=True, null=True, upload_to='automation/artifacts/%Y/%m/%d')),
                ('ai_failure_analysis', models.TextField(blank=True, null=True)),
                ('issues_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='automation.testexecution')),
            ],
            options={
                'db_table': 'automation_test_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_selector', models.CharField(max_length=1000)),
                ('healed_selector', models.CharField(max_length=1000)),
                ('detection_method', models.CharField(choices=[('dom', 'DOM'), ('text', 'Text'), ('vision_language', 'Vision Language'), ('hybrid', 'Hybrid')], max_length=30)),
                ('confidence_score', models.FloatField()),
                ('reason', models.TextField()),
                ('approved_automatically', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('escalated', 'Escalated'), ('rejected', 'Rejected')], max_length=20)),
                ('screenshot_before_url', models.URLField(blank=True, null=True)),
                ('screenshot_after_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healing_events', to='automation.testexecution')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='healing_events', to='automation.executionstep')),
            ],
            options={
                'db_table': 'automation_healing_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='executionstep',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='automation.testexecution'),
        ),
        migrations.CreateModel(
            name='ExecutionSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('cron_expression', models.CharField(max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('browser', models.CharField(choices=[('chromium', 'Chromium'), ('firefox', 'Firefox'), ('webkit', 'WebKit'), ('chrome', 'Chrome'), ('edge', 'Edge')], default='chromium', max_length=20)),
                ('platform', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')], default='desktop', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_execution_schedules', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_schedules', to='projects.project')),
                ('suite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_schedules', to='testing.testsuite')),
            ],
            options={
                'db_table': 'automation_execution_schedule',
                'ordering': ['project__name', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='executionstep',
            unique_together={('execution', 'step_index')},
        ),
    ]
