# Generated by Django 4.2.28 on 2026-04-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testexecution",
            name="agent_run",
        ),
        migrations.AlterField(
            model_name="testexecution",
            name="started_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="testexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("paused", "Paused"),
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                    ("error", "Error"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="queued",
                max_length=20,
            ),
        ),
    ]
