# Generated by Django 4.2.28 on 2026-04-13 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_batch6_execution_hardening'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealingEvent',
        ),
    ]
