# Generated by Django 4.2.28 on 2026-04-13 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('automation', '0005_remove_healing_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checkpoint_key', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='automation.testexecution')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_execution_checkpoints', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkpoints', to='automation.executionstep')),
            ],
            options={
                'db_table': 'automation_execution_checkpoint',
                'ordering': ['requested_at', 'checkpoint_key'],
            },
        ),
        migrations.AddConstraint(
            model_name='executioncheckpoint',
            constraint=models.UniqueConstraint(fields=('execution', 'checkpoint_key'), name='automation_unique_execution_checkpoint_key'),
        ),
    ]
