# Generated by Django 4.2.28 on 2026-04-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_live_execution_streaming'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='selenium_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='trigger_type',
            field=models.CharField(
                choices=[
                    ('manual', 'Manual'),
                    ('ci_cd', 'CI/CD'),
                    ('scheduled', 'Scheduled'),
                    ('webhook', 'Webhook'),
                    ('nightly', 'Nightly'),
                    ('diagnostic', 'Diagnostic'),
                ],
                default='manual',
                max_length=20,
            ),
        ),
    ]
