# Generated by Django 4.2.28 on 2026-05-10

from django.db import migrations, models


def backfill_artifact_storage_keys(apps, schema_editor):
    test_artifact = apps.get_model("automation", "TestArtifact")
    for artifact in test_artifact.objects.filter(storage_key="").iterator():
        artifact.storage_backend = "local"
        artifact.storage_key = artifact.storage_path
        artifact.save(update_fields=["storage_backend", "storage_key"])


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0007_testexecution_selenium_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="testartifact",
            name="storage_backend",
            field=models.CharField(
                choices=[("local", "Local"), ("minio", "MinIO")],
                default="local",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="testartifact",
            name="storage_key",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.RunPython(
            backfill_artifact_storage_keys,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="testexecution",
            name="debug_rerun",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="testexecution",
            name="stream_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
