# Generated by Django 4.2.28 on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0008_browser_storage_stream_seams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testartifact",
            name="storage_backend",
            field=models.CharField(
                choices=[("local", "Local"), ("minio", "MinIO")],
                default="minio",
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="testartifact",
            name="storage_path",
        ),
    ]
