# Generated by Django 4.2.28 on 2026-05-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_remove_testartifact_storage_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testexecution',
            name='trigger_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('ci_cd', 'CI/CD'), ('scheduled', 'Scheduled'), ('webhook', 'Webhook'), ('nightly', 'Nightly'), ('diagnostic', 'Diagnostic'), ('ai_authoring', 'AI Authoring')], default='manual', max_length=20),
        ),
    ]
