# Generated by Django 4.2.28 on 2026-05-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0010_alter_testexecution_trigger_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionstep',
            name='target_attrs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
