/** Modal editor for storing and updating automation scripts on a selected test case. */
import { useEffect, useState } from "react";

import { Button } from "../Button";
import { FormSelect } from "../FormSelect";
import { Modal } from "../Modal";
import type {
  AutomationFramework,
  AutomationLanguage,
  AutomationScript,
  AutomationScriptGeneratedBy,
  AutomationScriptWritePayload,
} from "../../types/automation";

interface AutomationScriptEditorModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (payload: AutomationScriptWritePayload) => Promise<void>;
  testCaseId: string | null;
  initialScript?: AutomationScript | null;
  isSaving?: boolean;
}

interface ScriptFormState {
  framework: AutomationFramework;
  language: AutomationLanguage;
  generatedBy: AutomationScriptGeneratedBy;
  isActive: boolean;
  scriptContent: string;
}

const initialFormState: ScriptFormState = {
  framework: "playwright",
  language: "python",
  generatedBy: "user",
  isActive: true,
  scriptContent: "",
};

const frameworkOptions = [
  { value: "playwright", label: "playwright" },
  { value: "selenium", label: "selenium" },
];

const languageOptions = [
  { value: "python", label: "python" },
  { value: "javascript", label: "javascript" },
  { value: "typescript", label: "typescript" },
  { value: "java", label: "java" },
];

const generatedByOptions = [
  { value: "user", label: "user" },
  { value: "ai", label: "ai" },
];

export function AutomationScriptEditorModal({
  isOpen,
  onClose,
  onSubmit,
  testCaseId,
  initialScript = null,
  isSaving = false,
}: Readonly<AutomationScriptEditorModalProps>) {
  const [form, setForm] = useState<ScriptFormState>(initialFormState);

  useEffect(() => {
    if (!isOpen) {
      return;
    }

    if (initialScript) {
      setForm({
        framework: initialScript.framework,
        language: initialScript.language,
        generatedBy: initialScript.generated_by,
        isActive: initialScript.is_active,
        scriptContent: initialScript.script_content,
      });
      return;
    }

    setForm(initialFormState);
  }, [initialScript, isOpen]);

  const handleSubmit = async () => {
    if (!testCaseId) {
      return;
    }

    await onSubmit({
      test_case: testCaseId,
      framework: form.framework,
      language: form.language,
      generated_by: form.generatedBy,
      is_active: form.isActive,
      script_content: form.scriptContent,
    });
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title={initialScript ? "Edit Automation Script" : "Add Automation Script"}
      size="xl"
    >
      <div className="space-y-4">
        <div className="grid gap-4 md:grid-cols-3">
          <FormSelect
            id="automation-script-framework"
            label="Framework"
            value={form.framework}
            onChange={(event) =>
              setForm((previous) => ({
                ...previous,
                framework: event.target.value as AutomationFramework,
              }))
            }
            options={frameworkOptions}
          />
          <FormSelect
            id="automation-script-language"
            label="Language"
            value={form.language}
            onChange={(event) =>
              setForm((previous) => ({
                ...previous,
                language: event.target.value as AutomationLanguage,
              }))
            }
            options={languageOptions}
          />
          <FormSelect
            id="automation-script-generated-by"
            label="Generated by"
            value={form.generatedBy}
            onChange={(event) =>
              setForm((previous) => ({
                ...previous,
                generatedBy: event.target.value as AutomationScriptGeneratedBy,
              }))
            }
            options={generatedByOptions}
          />
        </div>

        <label className="flex items-center gap-3 rounded-2xl border border-border bg-bg px-4 py-3 text-sm text-text">
          <input
            type="checkbox"
            checked={form.isActive}
            onChange={(event) =>
              setForm((previous) => ({
                ...previous,
                isActive: event.target.checked,
              }))
            }
            className="h-4 w-4 rounded border-border text-primary focus:ring-primary-light"
          />
          Keep this script active for the selected case
        </label>

        <div>
          <label
            htmlFor="automation-script-content"
            className="mb-2 block text-xs font-semibold uppercase tracking-[0.18em] text-muted"
          >
            Script content
          </label>
          <textarea
            id="automation-script-content"
            rows={16}
            value={form.scriptContent}
            onChange={(event) =>
              setForm((previous) => ({
                ...previous,
                scriptContent: event.target.value,
              }))
            }
            placeholder="Paste the Playwright or Selenium script here."
            className="w-full rounded-2xl border border-border bg-surface px-4 py-3 font-mono text-sm leading-6 text-text outline-none transition placeholder:text-muted focus-visible:ring-4 focus-visible:ring-primary-light/20"
          />
        </div>

        <div className="flex justify-end gap-3">
          <Button variant="secondary" onClick={onClose}>
            Cancel
          </Button>
          <Button
            onClick={() => void handleSubmit()}
            isLoading={isSaving}
            loadingText="Saving..."
            disabled={!testCaseId || !form.scriptContent.trim()}
          >
            {initialScript ? "Save Script" : "Create Script"}
          </Button>
        </div>
      </div>
    </Modal>
  );
}
