# Generated by Django 4.2.28 on 2026-04-02 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specs', '0004_specification_content_hash'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('folder_path', models.CharField(blank=True, default='', max_length=500)),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_suites', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_suites', to='projects.project')),
                ('specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_suites', to='specs.specification')),
            ],
            options={
                'db_table': 'testing_test_suite',
                'ordering': ['project__name', 'folder_path', 'name'],
                'unique_together': {('project', 'folder_path', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TestScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('scenario_type', models.CharField(choices=[('happy_path', 'Happy Path'), ('edge_case', 'Edge Case'), ('negative', 'Negative'), ('security', 'Security'), ('performance', 'Performance'), ('accessibility', 'Accessibility')], default='happy_path', max_length=30)),
                ('priority', models.CharField(choices=[('must_have', 'Must Have'), ('should_have', 'Should Have'), ('could_have', 'Could Have'), ('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('polarity', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], default='positive', max_length=20)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='testing.testsuite')),
            ],
            options={
                'db_table': 'testing_test_scenario',
                'ordering': ['suite__name', 'order_index', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('preconditions', models.TextField(blank=True)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('expected_result', models.TextField()),
                ('test_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='draft', max_length=20)),
                ('automation_status', models.CharField(choices=[('manual', 'Manual'), ('automated', 'Automated'), ('in_progress', 'In Progress')], default='manual', max_length=20)),
                ('ai_generated', models.BooleanField(default=False)),
                ('jira_issue_key', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.IntegerField(default=1)),
                ('on_failure', models.CharField(choices=[('fail_and_stop', 'Fail And Stop'), ('fail_but_continue', 'Fail But Continue')], default='fail_but_continue', max_length=30)),
                ('timeout_ms', models.IntegerField(default=120000)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='testing.testscenario')),
            ],
            options={
                'db_table': 'testing_test_case',
                'ordering': ['scenario__title', 'order_index', 'title'],
            },
        ),
    ]
