# Generated by Django 4.2.28 on 2026-04-12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


DEFAULT_SECTION_NAME = "General"
LEGACY_STATUS_MAP = {
    "draft": "draft",
    "ready": "approved",
    "running": "approved",
    "passed": "approved",
    "failed": "approved",
    "skipped": "approved",
    "in_review": "in_review",
    "approved": "approved",
    "archived": "archived",
}


def backfill_sections_and_revisions(apps, schema_editor):
    TestSuite = apps.get_model("testing", "TestSuite")
    TestSection = apps.get_model("testing", "TestSection")
    TestScenario = apps.get_model("testing", "TestScenario")
    TestCase = apps.get_model("testing", "TestCase")
    TestCaseRevision = apps.get_model("testing", "TestCaseRevision")

    default_sections_by_suite_id = {}
    for suite in TestSuite.objects.all().only("id").iterator():
        section = TestSection.objects.create(
            suite_id=suite.id,
            parent_id=None,
            name=DEFAULT_SECTION_NAME,
            order_index=0,
        )
        default_sections_by_suite_id[suite.id] = section.id

    for scenario in TestScenario.objects.all().only("id", "suite_id").iterator():
        section_id = default_sections_by_suite_id.get(scenario.suite_id)
        if section_id is None:
            section = TestSection.objects.create(
                suite_id=scenario.suite_id,
                parent_id=None,
                name=DEFAULT_SECTION_NAME,
                order_index=0,
            )
            section_id = section.id
            default_sections_by_suite_id[scenario.suite_id] = section_id

        TestScenario.objects.filter(pk=scenario.pk).update(section_id=section_id)

    for test_case in (
        TestCase.objects.select_related(
            "scenario",
            "scenario__suite",
            "scenario__suite__project",
        )
        .prefetch_related("linked_specifications")
        .all()
        .iterator()
    ):
        design_status = LEGACY_STATUS_MAP.get(test_case.design_status, "draft")
        if design_status != test_case.design_status:
            TestCase.objects.filter(pk=test_case.pk).update(design_status=design_status)

        version_number = test_case.version if (test_case.version or 0) > 0 else 1
        linked_specifications = list(test_case.linked_specifications.all())

        revision = TestCaseRevision.objects.create(
            test_case_id=test_case.id,
            version_number=version_number,
            title=test_case.title,
            preconditions=test_case.preconditions,
            steps=test_case.steps or [],
            expected_result=test_case.expected_result,
            test_data=test_case.test_data or {},
            source_snapshot_json={
                "migration_source": "batch4_repository_redesign",
                "scenario_id": str(test_case.scenario_id),
                "section_id": str(default_sections_by_suite_id.get(test_case.scenario.suite_id)),
                "suite_id": str(test_case.scenario.suite_id),
                "project_id": str(test_case.scenario.suite.project_id),
                "design_status": design_status,
                "automation_status": test_case.automation_status,
                "on_failure": test_case.on_failure,
                "timeout_ms": test_case.timeout_ms,
                "linked_specification_ids": [str(specification.id) for specification in linked_specifications],
                "migrated_from_version": test_case.version,
            },
            created_by_id=test_case.scenario.suite.created_by_id,
        )
        if linked_specifications:
            revision.linked_specifications.add(*linked_specifications)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("specs", "0005_embeddingmodel_specification_index_error_and_more"),
        ("testing", "0003_testcase_linked_specifications"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("order_index", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="testing.testsection",
                    ),
                ),
                (
                    "suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="testing.testsuite",
                    ),
                ),
            ],
            options={
                "db_table": "testing_test_section",
                "ordering": ["suite__name", "order_index", "name"],
                "unique_together": {("suite", "parent", "name")},
            },
        ),
        migrations.AddField(
            model_name="testscenario",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scenarios",
                to="testing.testsection",
            ),
        ),
        migrations.RenameField(
            model_name="testcase",
            old_name="status",
            new_name="design_status",
        ),
        migrations.AlterField(
            model_name="testcase",
            name="design_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_review", "In Review"),
                    ("approved", "Approved"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TestCaseRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.IntegerField()),
                ("title", models.CharField(max_length=500)),
                ("preconditions", models.TextField(blank=True)),
                ("steps", models.JSONField(blank=True, default=list)),
                ("expected_result", models.TextField()),
                ("test_data", models.JSONField(blank=True, default=dict)),
                ("source_snapshot_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_test_case_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="testing.testcase",
                    ),
                ),
            ],
            options={
                "db_table": "testing_test_case_revision",
                "ordering": ["-version_number", "-created_at"],
                "unique_together": {("test_case", "version_number")},
            },
        ),
        migrations.AddField(
            model_name="testcaserevision",
            name="linked_specifications",
            field=models.ManyToManyField(
                blank=True,
                related_name="linked_test_case_revisions",
                to="specs.specification",
            ),
        ),
        migrations.RunPython(backfill_sections_and_revisions, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="testscenario",
            options={
                "db_table": "testing_test_scenario",
                "ordering": [
                    "section__suite__name",
                    "section__order_index",
                    "order_index",
                    "title",
                ],
            },
        ),
        migrations.AlterField(
            model_name="testscenario",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scenarios",
                to="testing.testsection",
            ),
        ),
        migrations.RemoveField(
            model_name="testscenario",
            name="suite",
        ),
    ]
