from django.urls import path

from apps.ai.api.views import (
    AIAuthoringScriptSaveView,
    AIAuthoringSessionStartView,
    AIAuthoringTraceSaveView,
    AIGenerationSessionCommitView,
    AIGenerationSessionCancelView,
    AIGenerationSessionClarifyView,
    AIGenerationSessionDetailView,
    AIGenerationSessionListCreateView,
    AIGenerationSessionRefineView,
    AIGenerationSessionReviewView,
)

urlpatterns = [
    path(
        "ai/authoring/sessions/",
        AIAuthoringSessionStartView.as_view(),
        name="ai-authoring-session-start",
    ),
    path(
        "ai/authoring/sessions/<uuid:execution_pk>/save-trace/",
        AIAuthoringTraceSaveView.as_view(),
        name="ai-authoring-trace-save",
    ),
    path(
        "ai/authoring/sessions/<uuid:execution_pk>/save-script/",
        AIAuthoringScriptSaveView.as_view(),
        name="ai-authoring-script-save",
    ),
    path(
        "ai/generations/",
        AIGenerationSessionListCreateView.as_view(),
        name="ai-generation-list-create",
    ),
    path(
        "ai/generations/<uuid:pk>/",
        AIGenerationSessionDetailView.as_view(),
        name="ai-generation-detail",
    ),
    path(
        "ai/generations/<uuid:pk>/review/",
        AIGenerationSessionReviewView.as_view(),
        name="ai-generation-review",
    ),
    path(
        "ai/generations/<uuid:pk>/commit/",
        AIGenerationSessionCommitView.as_view(),
        name="ai-generation-commit",
    ),
    path(
        "ai/generations/<uuid:pk>/cancel/",
        AIGenerationSessionCancelView.as_view(),
        name="ai-generation-cancel",
    ),
    path(
        "ai/generations/<uuid:pk>/clarify/",
        AIGenerationSessionClarifyView.as_view(),
        name="ai-generation-clarify",
    ),
    path(
        "ai/generations/<uuid:pk>/refine/",
        AIGenerationSessionRefineView.as_view(),
        name="ai-generation-refine",
    ),
]
